name: ansible_ap
description: ActivityPub + HTTP Signature helpers for Ansible
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.10.0

dependencies:
  ansible_domain:
    path: ../domain
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  lints: ^6.0.0
  test: ^1.21.0
