name: ansible_relay
description: Ansible relay server (headless, autoscale)
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.10.0

dependencies:
  ansible_sync:
    path: ../../ansible_sync/handlers
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  args: ^2.4.0
  ansible_store:
    path: ../../ansible_core/store

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
