name: ansible_vc
description: VC models, issue/verify, StatusList for Ansible
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.10.0

dependencies:
  ansible_domain:
    path: ../domain
  ansible_did:
    path: ../did

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
