name: ansible_store
description: Ansible entities & repositories + Drift schema
publish_to: none
version: 0.1.0
environment:
  sdk: ^3.10.0

dependencies:
  ansible_domain:
    path: ../domain
  drift: ^2.4.0
  sqlite3: ^2.9.4

dev_dependencies:
  drift_dev: ^2.4.0
  build_runner: ^2.3.0
  lints: ^6.0.0
  test: ^1.21.0
